# render.yaml for Jam-Date application

services:
  # Backend (Flask API) service
  - type: web
    name: jamdate-backend
    env: python
    region: ohio  # or your preferred region
    buildCommand: |
      cd backend && pip install -r requirements.txt
      FLASK_APP=wsgi.py flask db upgrade
    startCommand: gunicorn --chdir backend wsgi:app
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: jamdate-db
          property: connectionString
      - key: JWT_SECRET_KEY
        generateValue: true
      - key: FLASK_ENV
        value: production
      - key: CORS_ORIGINS
        value: https://jamdate-frontend.onrender.com  

  # Frontend (Vue.js) service
  - type: static
    name: jamdate-frontend
    buildCommand: |
      npm install
      npm run build
    publish: dist
    envVars:
      - key: VITE_API_BASE_URL
        value: https://jamdate-backend.onrender.com  # Update with your backend URL

databases:
  - name: jamdate-db
    region: ohio
    plan: free  # or upgrade if needed
    databaseName: jamdate
    user: jamdate_user
